import type { Metadata } from "next";
import { Plus_Jakarta_Sans as FontSans } from "next/font/google";
import "./globals.css";
import { Navbar } from "./(Home)/Navbar";
import { cn } from "@/lib/utils";

// const montserrat = Montserrat({
//   variable: "--font-montserrat",
//   subsets: ["latin"],
// });

const fontSans = FontSans({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700","800"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
     <body
        className={cn(
          "font-sans antialiased",
          fontSans.variable
        )}
      >
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
